/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSozlamalarRouteImport } from './routes/_authenticated/sozlamalar'
import { Route as AuthenticatedLidlarRouteImport } from './routes/_authenticated/lidlar'
import { Route as AuthenticatedHisobotlarRouteImport } from './routes/_authenticated/hisobotlar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSozlamalarRoute = AuthenticatedSozlamalarRouteImport.update({
  id: '/_authenticated/sozlamalar',
  path: '/sozlamalar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLidlarRoute = AuthenticatedLidlarRouteImport.update({
  id: '/_authenticated/lidlar',
  path: '/lidlar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHisobotlarRoute = AuthenticatedHisobotlarRouteImport.update({
  id: '/_authenticated/hisobotlar',
  path: '/hisobotlar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hisobotlar': typeof AuthenticatedHisobotlarRoute
  '/lidlar': typeof AuthenticatedLidlarRoute
  '/sozlamalar': typeof AuthenticatedSozlamalarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hisobotlar': typeof AuthenticatedHisobotlarRoute
  '/lidlar': typeof AuthenticatedLidlarRoute
  '/sozlamalar': typeof AuthenticatedSozlamalarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/hisobotlar': typeof AuthenticatedHisobotlarRoute
  '/_authenticated/lidlar': typeof AuthenticatedLidlarRoute
  '/_authenticated/sozlamalar': typeof AuthenticatedSozlamalarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hisobotlar' | '/lidlar' | '/sozlamalar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hisobotlar' | '/lidlar' | '/sozlamalar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/hisobotlar'
    | '/_authenticated/lidlar'
    | '/_authenticated/sozlamalar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedHisobotlarRoute: typeof AuthenticatedHisobotlarRoute
  AuthenticatedLidlarRoute: typeof AuthenticatedLidlarRoute
  AuthenticatedSozlamalarRoute: typeof AuthenticatedSozlamalarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sozlamalar': {
      id: '/_authenticated/sozlamalar'
      path: '/sozlamalar'
      fullPath: '/sozlamalar'
      preLoaderRoute: typeof AuthenticatedSozlamalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lidlar': {
      id: '/_authenticated/lidlar'
      path: '/lidlar'
      fullPath: '/lidlar'
      preLoaderRoute: typeof AuthenticatedLidlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hisobotlar': {
      id: '/_authenticated/hisobotlar'
      path: '/hisobotlar'
      fullPath: '/hisobotlar'
      preLoaderRoute: typeof AuthenticatedHisobotlarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedHisobotlarRoute: AuthenticatedHisobotlarRoute,
  AuthenticatedLidlarRoute: AuthenticatedLidlarRoute,
  AuthenticatedSozlamalarRoute: AuthenticatedSozlamalarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
