/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PlatformaRouteImport } from './routes/platforma'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSozlamalarRouteImport } from './routes/_authenticated/sozlamalar'
import { Route as AuthenticatedMeningLidlarimRouteImport } from './routes/_authenticated/mening-lidlarim'
import { Route as AuthenticatedLidlarRouteImport } from './routes/_authenticated/lidlar'
import { Route as AuthenticatedKalendarRouteImport } from './routes/_authenticated/kalendar'
import { Route as AuthenticatedHisobotlarRouteImport } from './routes/_authenticated/hisobotlar'
import { Route as AuthenticatedBemorlarRouteImport } from './routes/_authenticated/bemorlar'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedBemorlarIdRouteImport } from './routes/_authenticated/bemorlar.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformaRoute = PlatformaRouteImport.update({
  id: '/platforma',
  path: '/platforma',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSozlamalarRoute = AuthenticatedSozlamalarRouteImport.update({
  id: '/sozlamalar',
  path: '/sozlamalar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeningLidlarimRoute =
  AuthenticatedMeningLidlarimRouteImport.update({
    id: '/mening-lidlarim',
    path: '/mening-lidlarim',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLidlarRoute = AuthenticatedLidlarRouteImport.update({
  id: '/lidlar',
  path: '/lidlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalendarRoute = AuthenticatedKalendarRouteImport.update({
  id: '/kalendar',
  path: '/kalendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHisobotlarRoute = AuthenticatedHisobotlarRouteImport.update({
  id: '/hisobotlar',
  path: '/hisobotlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBemorlarRoute = AuthenticatedBemorlarRouteImport.update({
  id: '/bemorlar',
  path: '/bemorlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBemorlarIdRoute = AuthenticatedBemorlarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBemorlarRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/platforma': typeof PlatformaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/bemorlar': typeof AuthenticatedBemorlarRouteWithChildren
  '/hisobotlar': typeof AuthenticatedHisobotlarRoute
  '/kalendar': typeof AuthenticatedKalendarRoute
  '/lidlar': typeof AuthenticatedLidlarRoute
  '/mening-lidlarim': typeof AuthenticatedMeningLidlarimRoute
  '/sozlamalar': typeof AuthenticatedSozlamalarRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/bemorlar/$id': typeof AuthenticatedBemorlarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/platforma': typeof PlatformaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/bemorlar': typeof AuthenticatedBemorlarRouteWithChildren
  '/hisobotlar': typeof AuthenticatedHisobotlarRoute
  '/kalendar': typeof AuthenticatedKalendarRoute
  '/lidlar': typeof AuthenticatedLidlarRoute
  '/mening-lidlarim': typeof AuthenticatedMeningLidlarimRoute
  '/sozlamalar': typeof AuthenticatedSozlamalarRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/bemorlar/$id': typeof AuthenticatedBemorlarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/platforma': typeof PlatformaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/bemorlar': typeof AuthenticatedBemorlarRouteWithChildren
  '/_authenticated/hisobotlar': typeof AuthenticatedHisobotlarRoute
  '/_authenticated/kalendar': typeof AuthenticatedKalendarRoute
  '/_authenticated/lidlar': typeof AuthenticatedLidlarRoute
  '/_authenticated/mening-lidlarim': typeof AuthenticatedMeningLidlarimRoute
  '/_authenticated/sozlamalar': typeof AuthenticatedSozlamalarRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/bemorlar/$id': typeof AuthenticatedBemorlarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/mcp'
    | '/platforma'
    | '/privacy-policy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/bemorlar'
    | '/hisobotlar'
    | '/kalendar'
    | '/lidlar'
    | '/mening-lidlarim'
    | '/sozlamalar'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/bemorlar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/mcp'
    | '/platforma'
    | '/privacy-policy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/bemorlar'
    | '/hisobotlar'
    | '/kalendar'
    | '/lidlar'
    | '/mening-lidlarim'
    | '/sozlamalar'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/bemorlar/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/mcp'
    | '/platforma'
    | '/privacy-policy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/bemorlar'
    | '/_authenticated/hisobotlar'
    | '/_authenticated/kalendar'
    | '/_authenticated/lidlar'
    | '/_authenticated/mening-lidlarim'
    | '/_authenticated/sozlamalar'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/bemorlar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PlatformaRoute: typeof PlatformaRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforma': {
      id: '/platforma'
      path: '/platforma'
      fullPath: '/platforma'
      preLoaderRoute: typeof PlatformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sozlamalar': {
      id: '/_authenticated/sozlamalar'
      path: '/sozlamalar'
      fullPath: '/sozlamalar'
      preLoaderRoute: typeof AuthenticatedSozlamalarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mening-lidlarim': {
      id: '/_authenticated/mening-lidlarim'
      path: '/mening-lidlarim'
      fullPath: '/mening-lidlarim'
      preLoaderRoute: typeof AuthenticatedMeningLidlarimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lidlar': {
      id: '/_authenticated/lidlar'
      path: '/lidlar'
      fullPath: '/lidlar'
      preLoaderRoute: typeof AuthenticatedLidlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalendar': {
      id: '/_authenticated/kalendar'
      path: '/kalendar'
      fullPath: '/kalendar'
      preLoaderRoute: typeof AuthenticatedKalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hisobotlar': {
      id: '/_authenticated/hisobotlar'
      path: '/hisobotlar'
      fullPath: '/hisobotlar'
      preLoaderRoute: typeof AuthenticatedHisobotlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bemorlar': {
      id: '/_authenticated/bemorlar'
      path: '/bemorlar'
      fullPath: '/bemorlar'
      preLoaderRoute: typeof AuthenticatedBemorlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bemorlar/$id': {
      id: '/_authenticated/bemorlar/$id'
      path: '/$id'
      fullPath: '/bemorlar/$id'
      preLoaderRoute: typeof AuthenticatedBemorlarIdRouteImport
      parentRoute: typeof AuthenticatedBemorlarRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBemorlarRouteChildren {
  AuthenticatedBemorlarIdRoute: typeof AuthenticatedBemorlarIdRoute
}

const AuthenticatedBemorlarRouteChildren: AuthenticatedBemorlarRouteChildren = {
  AuthenticatedBemorlarIdRoute: AuthenticatedBemorlarIdRoute,
}

const AuthenticatedBemorlarRouteWithChildren =
  AuthenticatedBemorlarRoute._addFileChildren(
    AuthenticatedBemorlarRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBemorlarRoute: typeof AuthenticatedBemorlarRouteWithChildren
  AuthenticatedHisobotlarRoute: typeof AuthenticatedHisobotlarRoute
  AuthenticatedKalendarRoute: typeof AuthenticatedKalendarRoute
  AuthenticatedLidlarRoute: typeof AuthenticatedLidlarRoute
  AuthenticatedMeningLidlarimRoute: typeof AuthenticatedMeningLidlarimRoute
  AuthenticatedSozlamalarRoute: typeof AuthenticatedSozlamalarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBemorlarRoute: AuthenticatedBemorlarRouteWithChildren,
  AuthenticatedHisobotlarRoute: AuthenticatedHisobotlarRoute,
  AuthenticatedKalendarRoute: AuthenticatedKalendarRoute,
  AuthenticatedLidlarRoute: AuthenticatedLidlarRoute,
  AuthenticatedMeningLidlarimRoute: AuthenticatedMeningLidlarimRoute,
  AuthenticatedSozlamalarRoute: AuthenticatedSozlamalarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PlatformaRoute: PlatformaRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
