/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformaRouteImport } from './routes/platforma'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArizaRouteImport } from './routes/ariza'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSozlamalarRouteImport } from './routes/_authenticated/sozlamalar'
import { Route as AuthenticatedMeningLidlarimRouteImport } from './routes/_authenticated/mening-lidlarim'
import { Route as AuthenticatedLidlarRouteImport } from './routes/_authenticated/lidlar'
import { Route as AuthenticatedKalendarRouteImport } from './routes/_authenticated/kalendar'
import { Route as AuthenticatedHisobotlarRouteImport } from './routes/_authenticated/hisobotlar'

const PlatformaRoute = PlatformaRouteImport.update({
  id: '/platforma',
  path: '/platforma',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArizaRoute = ArizaRouteImport.update({
  id: '/ariza',
  path: '/ariza',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSozlamalarRoute = AuthenticatedSozlamalarRouteImport.update({
  id: '/sozlamalar',
  path: '/sozlamalar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeningLidlarimRoute =
  AuthenticatedMeningLidlarimRouteImport.update({
    id: '/mening-lidlarim',
    path: '/mening-lidlarim',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLidlarRoute = AuthenticatedLidlarRouteImport.update({
  id: '/lidlar',
  path: '/lidlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalendarRoute = AuthenticatedKalendarRouteImport.update({
  id: '/kalendar',
  path: '/kalendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHisobotlarRoute = AuthenticatedHisobotlarRouteImport.update({
  id: '/hisobotlar',
  path: '/hisobotlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ariza': typeof ArizaRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/platforma': typeof PlatformaRoute
  '/hisobotlar': typeof AuthenticatedHisobotlarRoute
  '/kalendar': typeof AuthenticatedKalendarRoute
  '/lidlar': typeof AuthenticatedLidlarRoute
  '/mening-lidlarim': typeof AuthenticatedMeningLidlarimRoute
  '/sozlamalar': typeof AuthenticatedSozlamalarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ariza': typeof ArizaRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/platforma': typeof PlatformaRoute
  '/hisobotlar': typeof AuthenticatedHisobotlarRoute
  '/kalendar': typeof AuthenticatedKalendarRoute
  '/lidlar': typeof AuthenticatedLidlarRoute
  '/mening-lidlarim': typeof AuthenticatedMeningLidlarimRoute
  '/sozlamalar': typeof AuthenticatedSozlamalarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ariza': typeof ArizaRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/platforma': typeof PlatformaRoute
  '/_authenticated/hisobotlar': typeof AuthenticatedHisobotlarRoute
  '/_authenticated/kalendar': typeof AuthenticatedKalendarRoute
  '/_authenticated/lidlar': typeof AuthenticatedLidlarRoute
  '/_authenticated/mening-lidlarim': typeof AuthenticatedMeningLidlarimRoute
  '/_authenticated/sozlamalar': typeof AuthenticatedSozlamalarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ariza'
    | '/auth'
    | '/login'
    | '/platforma'
    | '/hisobotlar'
    | '/kalendar'
    | '/lidlar'
    | '/mening-lidlarim'
    | '/sozlamalar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ariza'
    | '/auth'
    | '/login'
    | '/platforma'
    | '/hisobotlar'
    | '/kalendar'
    | '/lidlar'
    | '/mening-lidlarim'
    | '/sozlamalar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ariza'
    | '/auth'
    | '/login'
    | '/platforma'
    | '/_authenticated/hisobotlar'
    | '/_authenticated/kalendar'
    | '/_authenticated/lidlar'
    | '/_authenticated/mening-lidlarim'
    | '/_authenticated/sozlamalar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArizaRoute: typeof ArizaRoute
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  PlatformaRoute: typeof PlatformaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platforma': {
      id: '/platforma'
      path: '/platforma'
      fullPath: '/platforma'
      preLoaderRoute: typeof PlatformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ariza': {
      id: '/ariza'
      path: '/ariza'
      fullPath: '/ariza'
      preLoaderRoute: typeof ArizaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sozlamalar': {
      id: '/_authenticated/sozlamalar'
      path: '/sozlamalar'
      fullPath: '/sozlamalar'
      preLoaderRoute: typeof AuthenticatedSozlamalarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mening-lidlarim': {
      id: '/_authenticated/mening-lidlarim'
      path: '/mening-lidlarim'
      fullPath: '/mening-lidlarim'
      preLoaderRoute: typeof AuthenticatedMeningLidlarimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lidlar': {
      id: '/_authenticated/lidlar'
      path: '/lidlar'
      fullPath: '/lidlar'
      preLoaderRoute: typeof AuthenticatedLidlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalendar': {
      id: '/_authenticated/kalendar'
      path: '/kalendar'
      fullPath: '/kalendar'
      preLoaderRoute: typeof AuthenticatedKalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hisobotlar': {
      id: '/_authenticated/hisobotlar'
      path: '/hisobotlar'
      fullPath: '/hisobotlar'
      preLoaderRoute: typeof AuthenticatedHisobotlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHisobotlarRoute: typeof AuthenticatedHisobotlarRoute
  AuthenticatedKalendarRoute: typeof AuthenticatedKalendarRoute
  AuthenticatedLidlarRoute: typeof AuthenticatedLidlarRoute
  AuthenticatedMeningLidlarimRoute: typeof AuthenticatedMeningLidlarimRoute
  AuthenticatedSozlamalarRoute: typeof AuthenticatedSozlamalarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHisobotlarRoute: AuthenticatedHisobotlarRoute,
  AuthenticatedKalendarRoute: AuthenticatedKalendarRoute,
  AuthenticatedLidlarRoute: AuthenticatedLidlarRoute,
  AuthenticatedMeningLidlarimRoute: AuthenticatedMeningLidlarimRoute,
  AuthenticatedSozlamalarRoute: AuthenticatedSozlamalarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArizaRoute: ArizaRoute,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  PlatformaRoute: PlatformaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
